-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgZC5cQfJH8RdpOUWX
2ufm9PqWhtLr8yd9ldSeW7HOxsigCgYIKoZIzj0DAQehRANCAAQRY5a+GBRNlDiF
cvfAeEfM9MaxkFbM3/LzSGUjVi77p+9usVUmWYSqwwfDBPO63bieiKBS9Z9HH/M0
QvIR/Vuj
-----END PRIVATE KEY-----